# https://www.rplumber.io/articles/hosting.html

name: tfm-r-server
services:
  r-plumber:
    build: .
    #command: /api/start.R
    volumes:
      - ./api:/api
      - ./FTM-R:/r
      - ./.env:/.env
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      apikey: ${SUPABASE_KEY}
    restart: unless-stopped
    ports:
     - "7005:8000"